### ISSUE TITLE
User onboarding

### ISSUE THREAD

**Issue by timlinux** [landinfotech/mycivitas#88]
@Andrevdb and Tjaart Please see below for our proposed user onboarding process.

![CMMS-User-Onboarding](https://user-images.githubusercontent.com/178003/122026072-d4f2db80-cdc1-11eb-8bb6-7f9b0781915c.png)

[CMMS-User-Onboarding.zip](https://github.com/landinfotech/civitas-asset-management/files/6654347/CMMS-User-Onboarding.zip)

@meomancer will start to build this after finalising some of the map issues. Please add any comments here if you want to suggest changes to the workflow.

Also @Andrevdb can you please provide a collection of around 10 nice scenic images from the communities you visit so that we can embellish our onboarding pages?

**Comment by Andrevdb** [comment]
Here's a folder with some images. @tjaartvdb Let's add more here as they come in! https://drive.google.com/drive/folders/17Nv6i3v1MfwN-SKaOdnxv4qIGFRRoIKo?usp=sharing

**Comment by Andrevdb** [comment]
@meomancer @timlinux Thanks for the onboarding process flow. This looks amazing!

A couple of ideas:
- Could we add some way to have a "promo code" to give communities the ability to freely test the application with their data?
- In addition to the Django userbase, there is also a single QGIS technician user configured per community. It will be nice to have this QGIS user configured even if a community has not signed up with Civitas in order to digitize data/etc. Perhaps it makes sense to configure a QGIS user for each community that is listed in the community list - ideally automatically, using a trigger or something, whenever a community is added. I don't think this QGIS user should count towards the purchased # of users, and shouldn't be able to log in to the web app - so we can keep it separate for both databases. If a community wants to have access to this QGIS technician user, they can contact us directly? Or should we send out the username/password with signup? What do you think @tjaartvdb ?

**Comment by tjaartvdb** [comment]
QGIS Technician user sign-up: In the short to medium term, it should work if the community contact us directly - Long term it will be good to generate a username/password when the community signs up. @Andrevdb @meomancer @timlinux

**Comment by meomancer** [comment]
TODO:
Currently, the invitation will be directly added to organisation user, It should be an invitation, so:

 - [ ] Add Notification system (it will show invitations)
 - [ ] Invited user needs to accept, or reject it
 - [ ] Delete user role, it will also send notification
 - [ ] Able to invite just email, it will send link to the user's email, sign in, and automatically show the invitation in the notification

**Comment by Andrevdb** [comment]
I'm going to close this for now and make update the flow chart to the existing process.
